### ISSUE TITLE
Review Model

### ISSUE THREAD

**Issue by servo98** [los-tucanes-de-la-web/api-backend#3]

**Comment by faustogute** [comment]
const reviewSchema = new mongoose.Schema({
  comment: String,
  rating: Number,
  movie: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Movie'
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  enabled: Boolean
})
